version: "3.8"

# Local development override - disables Traefik and uses direct port access
services:
  webserver:
    networks:
      - ${CLIENT_NAME:-widgetsrus}website
    build:
      context: ./bin/webserver
    container_name: "${CLIENT_NAME:-widgetsrus}website"
    restart: "always"
    hostname: ${WP_DOMAIN:-widgetsrus.local}
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT:-80}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT:-443}:443"
    volumes:
      - ${DOCUMENT_ROOT:-./public_html}:/var/www/${CLIENT_NAME:-widgetsrus}.local/public_html:cached
      - ${PHP_INI:-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR:-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR:-./logs/apache2}:/var/log/apache2
    labels: []  # Disable Traefik labels for local development
    depends_on:
      - database
    environment:
      - WORDPRESS_DB_HOST=${MYSQL_HOST:-database}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}

  database:
    networks:
      - ${CLIENT_NAME:-widgetsrus}website
    image: mysql:8.0
    command: --log_bin_trust_function_creators=1 --default-authentication-plugin=mysql_native_password
    container_name: "${CLIENT_NAME:-widgetsrus}mysql"
    restart: "always"
    ports:
      - "${HOST_MACHINE_MYSQL_PORT:-3306}:3306"
    volumes:
      - ${MYSQL_DATA_DIR:-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR:-./logs/mysql}:/var/log/mysql
      - ./bin/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    deploy:
      resources:
        limits:
          cpus: "${MYSQL_CPU_LIMIT:-4}"
          memory: ${MYSQL_MEMORY_LIMIT:-16G}

networks:
  ${CLIENT_NAME:-widgetsrus}website:
    driver: bridge