#!/bin/bash

# WordPress Containerized Client Setup Script
# Installs WordPress core, configures database, and sets up required plugins

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Determine environment from .env file
ENVIRONMENT="${ENVIRONMENT:-unknown}"
if [ -f ".env" ]; then
    ENVIRONMENT=$(grep "^ENVIRONMENT=" .env | cut -d'=' -f2 | tr -d '"' | tr -d "'")
fi

# Safety check - prevent re-running setup for same environment
if [ -f ".setup-complete-${ENVIRONMENT}" ]; then
    log_warn "Setup already completed for ${ENVIRONMENT} environment."
    log_info "If you need to re-run setup for this environment, delete .setup-complete-${ENVIRONMENT} file first."
    exit 0
fi

log_info "Starting WordPress client setup..."

# Check if .env file exists
if [ ! -f ".env" ]; then
    if [ -f ".env.template" ]; then
        log_info "Creating .env from template..."
        cp .env.template .env
        log_warn "Please edit .env file with your configuration before continuing."
        log_info "Press Enter when ready to continue..."
        read -r
    else
        log_error ".env file not found and no template available."
        exit 1
    fi
fi

# Load environment variables
set -a
source .env
set +a

# Validate required environment variables
REQUIRED_VARS=(
    "ENVIRONMENT"
    "MYSQL_DATABASE"
    "MYSQL_USER"
    "MYSQL_PASSWORD"
    "MYSQL_ROOT_PASSWORD"
    "WP_DOMAIN"
    "WP_TITLE"
    "WP_ADMIN_USER"
    "WP_ADMIN_PASSWORD"
    "WP_ADMIN_EMAIL"
)

for var in "${REQUIRED_VARS[@]}"; do
    if [ -z "${!var}" ]; then
        log_error "Required environment variable $var is not set in .env file"
        exit 1
    fi
done

# Set WordPress path and container names
WP_PATH="${DOCUMENT_ROOT:-./public_html}"
WEBSERVER_CONTAINER="${CONTAINER_PREFIX:-client}-webserver-${ENVIRONMENT:-staging}"
DATABASE_CONTAINER="${CONTAINER_PREFIX:-client}-mysql-${ENVIRONMENT:-staging}"

log_info "WordPress will be installed to: $WP_PATH"
log_info "Environment: $ENVIRONMENT"

# Create WordPress directory if it doesn't exist
mkdir -p "$WP_PATH"

# Check if WordPress is already installed
if [ -f "$WP_PATH/wp-config.php" ]; then
    log_warn "WordPress already appears to be installed (wp-config.php exists)"
    log_info "Skipping WordPress installation..."
else
    log_info "Starting Docker containers..."
    
    # Start containers first
    docker-compose up -d
    
    # Wait for containers to be ready
    log_info "Waiting for containers to start..."
    sleep 10
    
    # Wait for database to be ready
    log_info "Waiting for database connection..."
    max_attempts=30
    attempt=1
    
    while ! docker exec "$DATABASE_CONTAINER" mysqladmin ping -h localhost --silent 2>/dev/null; do
        if [ $attempt -eq $max_attempts ]; then
            log_error "Database failed to start after $max_attempts attempts"
            exit 1
        fi
        log_info "Attempt $attempt/$max_attempts: Waiting for database..."
        sleep 5
        ((attempt++))
    done

    log_info "Database is ready"

    # Download WordPress core
    log_info "Downloading WordPress core..."
    docker exec "$WEBSERVER_CONTAINER" wp core download --path=/var/www/html --allow-root

    # Generate wp-config.php using WP-CLI
    log_info "Creating WordPress configuration..."
    docker exec "$WEBSERVER_CONTAINER" wp config create \
        --path=/var/www/html \
        --dbname="$MYSQL_DATABASE" \
        --dbuser="$MYSQL_USER" \
        --dbpass="$MYSQL_PASSWORD" \
        --dbhost="$DATABASE_CONTAINER" \
        --allow-root
    log_info "wp-config.php generated by WP-CLI"

    # Install WordPress
    log_info "Installing WordPress..."
    docker exec "$WEBSERVER_CONTAINER" wp core install \
        --path=/var/www/html \
        --url="$WP_DOMAIN" \
        --title="$WP_TITLE" \
        --admin_user="$WP_ADMIN_USER" \
        --admin_password="$WP_ADMIN_PASSWORD" \
        --admin_email="$WP_ADMIN_EMAIL" \
        --allow-root

    log_info "WordPress core installation completed"
fi

# Ensure containers are running for plugin installation
log_info "Ensuring containers are running..."
docker-compose up -d

# Install and configure plugins
log_info "Installing required plugins..."

# Install other plugins
PLUGINS=(
    "classic-editor"
    "wp-super-cache"
    "wordfence"
    "updraftplus"
)

for plugin in "${PLUGINS[@]}"; do
    if ! docker exec "$WEBSERVER_CONTAINER" wp plugin is-installed "$plugin" --path=/var/www/html --allow-root 2>/dev/null; then
        log_info "Installing plugin: $plugin"
        docker exec "$WEBSERVER_CONTAINER" wp plugin install "$plugin" --activate --path=/var/www/html --allow-root
    else
        log_info "Plugin already installed: $plugin"
    fi
done

# Configure WordPress settings
log_info "Configuring WordPress settings..."

# Set timezone
if [ -n "${WP_TIMEZONE:-}" ]; then
    docker exec "$WEBSERVER_CONTAINER" wp option update timezone_string "$WP_TIMEZONE" --path=/var/www/html --allow-root
fi

# Set permalink structure
docker exec "$WEBSERVER_CONTAINER" wp rewrite structure '/%postname%/' --path=/var/www/html --allow-root

# Update default options
docker exec "$WEBSERVER_CONTAINER" wp option update start_of_week 1 --path=/var/www/html --allow-root  # Monday
docker exec "$WEBSERVER_CONTAINER" wp option update date_format 'F j, Y' --path=/var/www/html --allow-root
docker exec "$WEBSERVER_CONTAINER" wp option update time_format 'g:i a' --path=/var/www/html --allow-root

# Remove default content (optional)
if [ "${REMOVE_DEFAULT_CONTENT:-true}" = "true" ]; then
    log_info "Removing default WordPress content..."
    docker exec "$WEBSERVER_CONTAINER" wp post delete 1 --force --path=/var/www/html --allow-root 2>/dev/null || true  # Hello World post
    docker exec "$WEBSERVER_CONTAINER" wp post delete 2 --force --path=/var/www/html --allow-root 2>/dev/null || true  # Sample page
    docker exec "$WEBSERVER_CONTAINER" wp comment delete 1 --force --path=/var/www/html --allow-root 2>/dev/null || true  # Default comment
fi

# Set file permissions
log_info "Setting file permissions..."
docker exec "$WEBSERVER_CONTAINER" find /var/www/html -type d -exec chmod 755 {} \;
docker exec "$WEBSERVER_CONTAINER" find /var/www/html -type f -exec chmod 644 {} \;
docker exec "$WEBSERVER_CONTAINER" chmod 600 /var/www/html/wp-config.php

# Install Node.js dependencies and run build
log_info "Setting up build configuration..."
if [ -f "settings.template.js" ]; then
    envsubst < settings.template.js > settings.js
    log_info "Generated settings.js from template"
else
    log_warn "settings.template.js not found - build system may not work correctly"
fi

log_info "Installing Node.js dependencies and building theme..."
if command -v npm &> /dev/null && [ -f "package.json" ]; then
    npm install
    npm run production
    log_info "Theme build completed"
else
    log_warn "npm not found or package.json missing - skipping theme build"
fi

# Mark setup as complete for this environment
log_info "Finalizing setup for ${ENVIRONMENT} environment..."
touch ".setup-complete-${ENVIRONMENT}"

# Remove template files for security (setup script preserved for other environments)
if [ -f ".env.template" ]; then
    rm .env.template
    log_info "Removed .env.template"
fi

if [ -f "settings.template.js" ]; then
    rm settings.template.js
    log_info "Removed settings.template.js"
fi

log_info "========================================="
log_info "WordPress setup completed for ${ENVIRONMENT}!"
log_info "========================================="
log_info "Environment: $ENVIRONMENT"
log_info "WordPress URL: https://$WP_DOMAIN"
log_info "Admin URL: https://$WP_DOMAIN/wp-admin/"
log_info "Admin User: $WP_ADMIN_USER"
log_info "Container Status:"
docker ps --filter "name=${CONTAINER_PREFIX:-client}" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
log_info "========================================="
log_info "Setup script preserved for other environments."
log_info "Your ${ENVIRONMENT} WordPress site is ready!"